export const cardImagesProps = [
    'fas fa-ankh',
    'fas fa-atom',
    'fas fa-pastafarianism',
    'fas fa-star-of-david',
    'fas fa-hamsa',
    'fas fa-yin-yang',
    'fas fa-bug',
    'fas fa-laptop-code',
    'fas fa-ankh',
    'fas fa-atom',
    'fas fa-pastafarianism',
    'fas fa-star-of-david',
    'fas fa-hamsa',
    'fas fa-yin-yang',
    'fas fa-bug',
    'fas fa-laptop-code',
]